name: i_gen
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.10.0 <4.0.0"
    flutter: 3.38.5

dependencies:
    flutter:
        sdk: flutter

    sqflite_common_ffi: ^2.4.0
    sqflite: ^2.4.0
    sqlite3: ^3.0.0
    get_it: ^8.0.0
    flutter_localizations:
        sdk: flutter
    intl: ^0.20.2
    flutter_typeahead: ^5.2.0
    google_fonts: ^7.0.0
    trina_grid: 2.0.1
    path_provider: ^2.1.5
    pdf: ^3.11.3
    path: ^1.9.1
    gal: ^2.3.2
    uuid: ^4.5.2
    shared_preferences: ^2.5.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    msix: ^3.16.9

flutter:
    generate: true
    uses-material-design: true
    fonts:
        - family: Noto Naskh Arabic
          fonts:
              - asset: assets/NotoNaskhArabic-VariableFont_wght.ttf
    assets:
        - assets/

msix_config:
    display_name: InvoGen
    publisher_display_name: Mouayad Alhamwi
    identity_name: mouayad.invoGen
    msix_version: 1.0.0.0
    app_installer: #<-- app installer configuration
        publish_folder_path: c:\users\mouayad\desktop\InvoGen
        hours_between_update_checks: 0
        automatic_background_task: true
        update_blocks_activation: true
        show_prompt: true
        force_update_from_any_version: false
